---
puppetsync:
  permitted_project_types:
    - pupmod
    - pupmod_skeleton
  plans:
    sync:
      #clone_git_repos: false
      stages:
        - install_gems
        - checkout_git_feature_branch_in_each_repo
        - pdk_update
        # - git_commit_changes
        # - ensure_github_fork
        # - ensure_git_remote
        # - git_push_to_remote
        # - ensure_gitlab_remote
        # - git_push_to_gitlab
        # - ensure_github_pr

    approve_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - approve_github_pr_for_each_repo

    merge_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - merge_github_pr_for_each_repo

jira:
  parent_issue: pdk-update
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Disable all tests in Travis CI pipeline for %COMPONENT%'
  # optional:
  subtask_story_points: 0
  subtask_description: 'Disable all tests in Travis CI pipeline for %COMPONENT%'
  subtask_assignee: true

git:
  # 0---------1---------2---------3---------4---------5---------6---------7|
  # (SIMP-XXXX) 12345678                                     |
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Disable Travis CI tests

    This patch disables ALL TESTS in modules' Travis CI pipelines.
    Deployment and diagnostic stages have been left to support near-term
    releases, however we will shortly migrate them elsewhere as well.

    %JIRA_SUBTASK% #close
    [%JIRA_PARENT_ISSUE%] #comment Updated %COMPONENT%

github:
  pr_user: DavidS  # This should be the account that *submitted* the PRs (Used
                   # by the idempotency checks when approving/merging PRs)
  approval_message: ':+1: :ghost:'
