---
puppetsync:
  permitted_project_types:
    - pupmod
    - pupmod_skeleton
  plans:
    sync:
      #clone_git_repos: false
      stages:
        # - install_gems
        - checkout_git_feature_branch_in_each_repo
        - ensure_jira_subtask
        - apply_puppet_role
        - modernize_gitlab_files
        - lint_gitlab_ci
        - git_commit_changes
        - ensure_github_fork
        - ensure_git_remote
        - git_push_to_remote
        - ensure_gitlab_remote
        - git_push_to_gitlab
        - ensure_github_pr

    approve_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - approve_github_pr_for_each_repo

    merge_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - merge_github_pr_for_each_repo

jira:
  parent_issue: SIMP-8139
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Update %COMPONENT% to latest common module assets'
  # optional:
  subtask_story_points: 0
  subtask_description: 'Ensure latest common module assets in %COMPONENT%'
  subtask_assignee: true

git:
  # 0---------1---------2---------3---------4---------5---------6---------7|
  # (SIMP-XXXX) 12345678                                     |
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Update to latest common assets

    %JIRA_SUBTASK% #close

github:
  pr_user: op-ct  # This should be the account that *submits* the PRs (Used as
                  #  part of the idempotency checks when approving/merging PRs)
  approval_message: ':+1: :ghost:'
